### ISSUE TITLE
conversions to be done by hand

### ISSUE THREAD

**Issue by davidfarmer** [mitchkeller/applied-combinatorics#14]
I think these changes have to be made by directly editing the source files:

1) Use "term" not "em" for words being defined

2) Convert overpic to svg, or whatever is appropriate.

**Comment by mitchkeller** [comment]
1. I definitely need to go through and deal with "term". Will give me a good excuse to start looking at creating an index, too, I guess.
2. See my suggestion on your [issue #6](https://github.com/davidfarmer/applied-combinatorics/issues/6) to see if there's a way that this could be at least partially automated. I know I'm going to have to look at all those figures manually in the end, but if they could be wrapped in `<latex-image-code>`, it would save me a lot of work.

**Comment by mitchkeller** [comment]
A grep through the source suggests that all the remaining `<em>` tags are really there for emphasis.
