### ISSUE TITLE
Typo: Section 8.1 at log(1+x)

### ISSUE THREAD

**Issue by fidelbc** [mitchkeller/applied-combinatorics#21]
In example 8.2, after integrating, there is a (-1)^{n+1} factor missing in \sum_{n=1}^\infty \frac{x^n}{n}.

A period seems to be missing as well (to end that sentence).

**Comment by mitchkeller** [comment]
Good catch. Added to the errata page. No idea how that's persisted for so long. We're starting classes this week, but once things settle down from that, I'm considering having a "locked" 2016 HTML version posted that matches the print version 100% as well as an interim version that fixes little typos like this.

**Comment by davidfarmer** [comment]
I understand having an HTML version that has identical content to the
print version, but I don't see why that version can't have fixed typos.
(More specifically, I suggest having the interim version at the official
URL.  If you want to have the locked version, people should have to
go there intentionally.)
