### ISSUE TITLE
Render issue in section 7.1

### ISSUE THREAD

**Issue by fidelbc** [mitchkeller/applied-combinatorics#22]
[Example 7.3](http://www.rellek.net/book/s_inclusion-exclusion_intro.html#exa_inclusion-exclusion_int-solns) seems to have some issues when rendering (screenshots: [1](https://ibin.co/2wgvIygdEhrf.png) and [2](https://ibin.co/2wgvgOV5uHUm.png)). An inequality is displayed with double \gt signs when maybe only one is intended. Source code seems to be fine since LaTeX source does not have this problem.

Not sure if this is a MathJax issue.

**Comment by mitchkeller** [comment]
The MBX source code contains both \gt and > in succession, which is what is producing the double greater than sign in the output. I'll get it fixed as time permits. Thanks for reporting.
