### ISSUE TITLE
Example 2.32

### ISSUE THREAD

**Issue by fidelbc** [mitchkeller/applied-combinatorics#26]
Should the suffix be 'RAREGENIUSES'?
Current suffix is 'RAREREGENIUSES', see [1].

[1]: http://www.rellek.net/book/s_strings_multinom.html#example-34

**Comment by mitchkeller** [comment]
Yeah, that's a typo. I'll have to double check the counts on all the letters, because I now don't trust any of it as it's written!

**Comment by fidelbc** [comment]
It seems like the counts are correct once 'RE' is removed, see sagecell at [1] for details.

[1]: https://x0.no/0v079

**Comment by mitchkeller** [comment]
Thanks for the code to check things. I was going to write something but have too much on my plate at the moment.
