### ISSUE TITLE
Location of linear order definition

### ISSUE THREAD

**Issue by fidelbc** [mitchkeller/applied-combinatorics#28]
Was looking at example 6.7 4, see [1], and it seems that the term "linear order" is used before it is defined. Definition appears 3 paragraphs later in that section, see [2]. Is this an issue?

[1]: http://www.rellek.net/book/s_posets_intro.html#p-683
[2]: http://www.rellek.net/book/s_posets_intro.html#p-686

**Comment by mitchkeller** [comment]
I've never really seen it as a problem, but I could also see a case for moving the paragraph that defines linear order (and the one following it) between Discussion 6.6 and Example 6.7.

**Comment by fidelbc** [comment]
Not sure how likely it is that a student has not seen that term before (maybe from other math/cs course?) while reading that section.  Just wanted to point it out in case you consider moving paragraphs might help some of the readers :-)
