### ISSUE TITLE
Exercise 2, section 7.7

### ISSUE THREAD

**Issue by fidelbc** [mitchkeller/applied-combinatorics#29]
Please see [1] for exercise statement.

There seems to be an issue with the number of students that know Java. There are 748 such students. Since 488 know all three languages then this leaves 748-488=260 students that know Java and at most one other language. Issue arises when you compute the number of students that know only Java and C++ (639-488=151), and only Java and Python (632-488=144). Since these sets are disjoint subsets of the students that know Java, we should have 144+151\leq 260, which is not possible.

Seems like a possible fix would be to add 35 students to the Java category, or maybe a bit more so that there are students that only know Java.

Credits go to an anonymous student who reported this.

[1]: http://www.rellek.net/book/s_inclusion-exclusion_exercises.html#p-879

**Comment by mitchkeller** [comment]
Finally getting around to cleaning up bugs. I've picked another number so that there are some students who know only Java and will have updated in the 2017 edition due out soon.
