### ISSUE TITLE
Website username example in strings chapter

### ISSUE THREAD

**Issue by mitchkeller** [mitchkeller/applied-combinatorics#4]
There's a tabular here that really shouldn't be one, and the \end{example} is misplaced.

**Comment by Aioxas** [comment]
Can you expand on why a tabular might not be appropriate? Unless you mean in the sense of the underlying code (in which it's a bunch of cells and hashes). Also, I don't see that the \end{example} is misplaced. Unless I am misunderstanding something.

**Comment by mitchkeller** [comment]
I'll have to look at the code, but I suspect that I moved the end tag for the example as part of the conversion to MBX. 

I suspect that a table could be the right solution, but as it's done now, it is *not* tabular data in a way that is friendly to a screen reader for a visually impaired reader. The table element should be used for presenting tabular data (with a lot of structure) and not just creating a convenient visual display.

**Comment by Aioxas** [comment]
Is there any way of reproducing a screen reader for a visually impaired reader in a computer to possibly test different practical solutions, if any arise? Because many ideas can be suggested, but none will actually make a difference if we can't visualize it from the point of view of the people concerned.

**Comment by mitchkeller** [comment]
The MBX author list has someone on it who’s knowledgeable about accessibility issues, and I have some additional contacts. Basically, tables should have well-defined headers for rows and columns. MBX tries to offer a good set of tools for designing in that manner, but it’s not something that’s fully imposed upon authors. I have a pretty good idea of what I want to do with this, but it’s not a high priority at the moment. (Mid-year updates are focused on things that will not create problematic differences between the print and HTML versions.)

> On Jan 25, 2017, at 13:33, Aioxas <notifications@github.com> wrote:
> 
> Is there any way of reproducing a screen reader for a visually impaired reader in a computer to possibly test different practical solutions, if any arise? Because many ideas can be suggested, but none will actually make a difference if we can't visualize it from the point of view of the people concerned.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Mitch Keller
Assistant Professor of Mathematics
Washington & Lee University, Lexington VA
206 Robinson Hall ~ 540.458.8099 ~ http://www.rellek.net

**Comment by mitchkeller** [comment]
I'm closing this, as I think we have settled on this being an acceptable use of `tabular`.
